# Generated by Django 4.1.7 on 2023-03-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, unique=True, verbose_name="name"),
                ),
                (
                    "affiliation",
                    models.CharField(max_length=500, verbose_name="affiliation"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="title"
                    ),
                ),
                (
                    "img_url",
                    models.URLField(
                        max_length=3000, null=True, verbose_name="image url"
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, unique=True, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "topic",
                "verbose_name_plural": "topics",
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="statement content")),
                ("date", models.DateField(verbose_name="date said")),
                (
                    "url",
                    models.URLField(
                        blank=True, null=True, verbose_name="statement url"
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        blank=True, null=True, verbose_name="review summary"
                    ),
                ),
                (
                    "review_url",
                    models.URLField(
                        max_length=3000, null=True, verbose_name="review url"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(blank=True, null=True, verbose_name="review date"),
                ),
                (
                    "img_url",
                    models.URLField(
                        blank=True, max_length=3000, null=True, verbose_name="image url"
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "promise"), (2, "claim")],
                        null=True,
                        verbose_name="statement type",
                    ),
                ),
                (
                    "editing_notes",
                    models.TextField(
                        blank=True,
                        help_text="internal use only",
                        null=True,
                        verbose_name="editing notes",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statements",
                        to="statements.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="statements",
                        to="statements.topic",
                        verbose_name="topics",
                    ),
                ),
            ],
            options={
                "verbose_name": "statement",
                "verbose_name_plural": "statements",
            },
        ),
    ]
