# Generated by Django 4.1.7 on 2023-03-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, unique=True, verbose_name="name"),
                ),
                (
                    "affiliation",
                    models.CharField(max_length=500, verbose_name="affiliation"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="title"
                    ),
                ),
                ("img_url", models.URLField(null=True, verbose_name="image url")),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, unique=True, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "topic",
                "verbose_name_plural": "topics",
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "True"), (2, "Half True"), (3, "False")],
                        null=True,
                        verbose_name="rating",
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, null=True, verbose_name="review"),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="reviewed_by",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statements",
                        to="statements.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="statements",
                        to="statements.topic",
                        verbose_name="topics",
                    ),
                ),
            ],
            options={
                "verbose_name": "statement",
                "verbose_name_plural": "statements",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("timestamp", models.DateTimeField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Other"),
                            (10, "Tweet"),
                            (11, "Haaretz"),
                            (12, "YNet"),
                        ],
                        default=10,
                    ),
                ),
                ("content", models.TextField()),
                ("note", models.TextField(blank=True)),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="statements.statement",
                    ),
                ),
            ],
            options={
                "unique_together": {("statement", "url")},
            },
        ),
    ]
