# Generated by Django 4.1.7 on 2023-03-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="review_date",
            field=models.DateField(blank=True, null=True, verbose_name="review_date"),
        ),
    ]
