# Generated by Django 4.1.7 on 2023-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="url",
            field=models.URLField(
                blank=True, max_length=3000, null=True, verbose_name="statement url"
            ),
        ),
    ]
