# Generated by Django 4.1.7 on 2023-03-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "person", "verbose_name_plural": "people"},
        ),
        migrations.AlterModelOptions(
            name="statement",
            options={"verbose_name": "statement", "verbose_name_plural": "statements"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "topic", "verbose_name_plural": "topics"},
        ),
        migrations.AddField(
            model_name="person",
            name="img_url",
            field=models.URLField(null=True, verbose_name="image url"),
        ),
        migrations.AddField(
            model_name="person",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="affiliation",
            field=models.CharField(max_length=500, verbose_name="affiliation"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=250, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="content",
            field=models.TextField(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="statements.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "True"), (2, "Half True"), (3, "False")],
                null=True,
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="review",
            field=models.TextField(blank=True, null=True, verbose_name="review"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="statements",
                to="statements.topic",
                verbose_name="topics",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=250, unique=True, verbose_name="title"),
        ),
    ]
