# Generated by Django 4.1.7 on 2023-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0002_alter_person_options_alter_statement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="reviewed_by",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="reviewed_by"
            ),
        ),
    ]
