# Generated by Django 4.1.7 on 2023-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0003_statement_created_at_statement_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="img_url",
            field=models.URLField(null=True),
        ),
    ]
