# Generated by Django 4.1.7 on 2023-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0004_statement_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="img_url",
            field=models.URLField(max_length=3000, null=True, verbose_name="image url"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="statement",
            name="img_url",
            field=models.URLField(max_length=3000, null=True),
        ),
    ]
