# Generated by Django 4.1.7 on 2023-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0005_alter_person_img_url_alter_resource_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="review_url",
            field=models.URLField(
                max_length=3000, null=True, verbose_name="review url"
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="review_date",
            field=models.DateField(verbose_name="review date"),
        ),
    ]
