# Generated by Django 4.1.7 on 2023-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0006_statement_review_url_alter_statement_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="review_date",
            field=models.DateField(null=True, verbose_name="review date"),
        ),
    ]
