# Generated by Django 4.1.7 on 2023-03-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0008_alter_statement_content_alter_statement_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="statement url"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="img_url",
            field=models.URLField(
                blank=True, max_length=3000, null=True, verbose_name="image url"
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="review_date",
            field=models.DateField(blank=True, null=True, verbose_name="review date"),
        ),
    ]
