# Generated by Django 4.1.7 on 2023-03-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0009_statement_url_alter_statement_img_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="detailed_content",
            field=models.TextField(
                blank=True,
                help_text="detailed article about this item",
                null=True,
                verbose_name="detailed content",
            ),
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
